apiVersion: v1 
kind: PersistentVolume
metadata:
  name: medilab-mysql-pv
  namespace: medilab-db-ns
spec:
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: local-storage   #local-storage MEANS I HAVE TAKEN OUR EC2 INSTANCE EBS VOLUME
  persistentVolumeReclaimPolicy: Retain
  hostPath:
   path: /tmp/medilab-app-data
